"""add_image_url_to_shopee_offer

Revision ID: 079cb5631e9c
Revises: db25305153a6
Create Date: 2026-05-16 19:39:52.058803

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079cb5631e9c'
down_revision = 'db25305153a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopee_offers', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopee_offers', 'image_url')
    # ### end Alembic commands ###
