"""create shopee_offers

Revision ID: 9e89a68403dd
Revises: 
Create Date: 2026-05-13 23:59:29.807050

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e89a68403dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopee_offers', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('shopee_offers', sa.Column('offer_id', sa.String(length=128), nullable=False))
    op.add_column('shopee_offers', sa.Column('name', sa.String(length=512), nullable=False))
    op.add_column('shopee_offers', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('shopee_offers', sa.Column('commission_rate', sa.Float(), nullable=False))
    op.add_column('shopee_offers', sa.Column('original_url', sa.String(length=2048), nullable=False))
    op.add_column('shopee_offers', sa.Column('short_url', sa.String(length=2048), nullable=False))
    op.add_column('shopee_offers', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('shopee_offers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_shopee_offers_offer_id'), 'shopee_offers', ['offer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopee_offers_offer_id'), table_name='shopee_offers')
    op.drop_column('shopee_offers', 'created_at')
    op.drop_column('shopee_offers', 'is_published')
    op.drop_column('shopee_offers', 'short_url')
    op.drop_column('shopee_offers', 'original_url')
    op.drop_column('shopee_offers', 'commission_rate')
    op.drop_column('shopee_offers', 'price')
    op.drop_column('shopee_offers', 'name')
    op.drop_column('shopee_offers', 'offer_id')
    op.drop_column('shopee_offers', 'id')
    # ### end Alembic commands ###
