"""remove is_published_x column

Revision ID: db25305153a6
Revises: 7c4e9d1b2a34
Create Date: 2026-05-16 10:17:49.677989

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db25305153a6'
down_revision = '7c4e9d1b2a34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopee_offers', 'is_published_x')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopee_offers', sa.Column('is_published_x', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
